### ISSUE TITLE
Support packages that work with just "make && make install"

### ISSUE THREAD

**Issue by wwalker** [chef-cookbooks/tar#26]
Could we please have support for packages that build and install without a configure step (such as atop (http://atoptool.nl/))?

This could either be via an if based on the existence of the configure script, or on an argument of some sort that means no_configure_step.   I fairly new to chef, so I don't know what way to handle this properly.

**Comment by hulu1522** [comment]
@wwalker You should look into the ['ark' cookbook](https://github.com/burtlo/ark) which has options to install, configure, and [install_with_make](https://github.com/burtlo/ark#actions).

**Comment by tas50** [comment]
This use case should be handled with the ark cookbook.
