### ISSUE TITLE
Add support for FreeBSD

### ISSUE THREAD

**Issue by Katoga** [chef-cookbooks/tar#42]
### Cookbook version
V1.1.0

### Chef-client version
12.17.44

### Platform Details
FreeBSD 11.0

#### include recipe
Make `tar` command available in the system.
#### use resource tar_extract
Unpack remote `tar.gz` archive using resource `tar_extract`.

### Steps to Reproduce:
1. clone this repo to machine with kitchen using vagrant: https://github.com/Katoga/test_tar
1. run `kitchen converge`
1. FreeBSD box will fail
1. Debian box will converge successfuly

#### include recipe
Command `tar` is ready to use.
#### use resource tar_extract
Source archive is downloaded and unpacked in `#{temp_dir}/tar-1.1.0`

#### include recipe
Chef run on FreeBSD fails because the system does not have package named `tar`:
```
       Converging 1 resources
       Recipe: tar::default
         * freebsd_package[tar] action install

           ================================================================================
           Error executing action `install` on resource 'freebsd_package[tar]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '69'
           ---- Begin output of pkg rquery '%v' tar ----
           STDOUT:
           STDERR:
           ---- End output of pkg rquery '%v' tar ----
           Ran pkg rquery '%v' tar returned 69


```
#### use resource tar_extract
Chef run on FreeBSD fails because the system does not have group named `root`:
```
       Converging 1 resources
       Recipe: test_tar::resource
         * tar_extract[https://github.com/chef-cookbooks/tar/archive/v1.1.0.tar.gz] action extract
           * directory[/tmp/kitchen/cache] action create (up to date)
           * remote_file[v1.1.0.tar.gz] action create
             * cannot determine group id for 'root', does the group exist on this system?
             ================================================================================
             Error executing action `create` on resource 'remote_file[v1.1.0.tar.gz]'
             ================================================================================

             Chef::Exceptions::GroupIDNotFound
             ---------------------------------
             cannot determine group id for 'root', does the group exist on this system?
```

**Comment by tas50** [comment]
I’m adding the Type: Jump In GitHub label to this issue. This is a great issue for someone to get their feet wet with and we’d love a PR to resolves the issue.

**Comment by iennae** [comment]
Thanks for the PR to solve this. This will get included in the next release of the cookbook.
